name: Build DR PRINT PRO Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "index-windows.html"
      - "main.js"
      - "package.json"
      - "DR_PRINT_PRO_icon.ico"
      - ".github/workflows/build-windows.yml"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Get DR PRINT PRO files
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Windows Setup
        run: npm run dist

      - name: Upload DR PRINT PRO Setup
        uses: actions/upload-artifact@v4
        with:
          name: DR-PRINT-PRO-Windows-Setup
          path: |
            dist/*.exe
          if-no-files-found: error
